language: c

matrix:
  include:

    - os: linux
      addons:
        apt:
          packages:
            - libcurl4-openssl-dev
            - libssl-dev
            - zlib1g-dev
            - libsdl2-dev
      script:
        - make

    - os: linux
      services:
        - docker
      before_install:
        - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash
      script:
        - docker exec -it emscripten make -f Makefile.js

    - os: osx
      osx_image: xcode10.3
      addons:
        homebrew:
          packages:
            - openssl
            - sdl2
      script:
        - make CFLAGS=-I$(brew --prefix)/opt/openssl/include LDFLAGS=-L$(brew --prefix)/opt/openssl/lib CONFIG_MACOS=y

    - os: osx
      osx_image: xcode10.3
      script:
        - make CONFIG_IOS=y CONFIG_FS_NET= CONFIG_SDL=
        - make clean
        - make CONFIG_IOS_SIMULATOR=y CONFIG_FS_NET= CONFIG_SDL=
